# Generated by Django 4.0.4 on 2022-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='images')),
                ('rate', models.FloatField()),
            ],
        ),
    ]
