# Generated by Django 4.0.4 on 2022-05-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_user_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
